CREATE TABLE `todolist` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `title` VARCHAR(128) NOT NULL DEFAULT '0' COMMENT '详细',
  `status` TINYINT(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态',
  `mtime` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '修改时间',
  `ctime` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;